# 1. 数据读取与存储

## read_csv

In [3]:
import pandas as pd

df = pd.read_csv("./Data/los_census.csv")
print(df)

     Zip Code  Total Population  Median Age  Total Males  Total Females  \
0       91371                 1        73.5            0              1
1       90001             57110        26.6        28468          28642
2       90002             51223        25.5        24876          26347
3       90003             66266        26.3        32631          33635
4       90004             62180        34.8        31302          30878
5       90005             37681        33.9        19299          18382
6       90006             59185        32.4        30254          28931
7       90007             40920        24.0        20915          20005
8       90008             32327        39.7        14477          17850
9       90010              3800        37.8         1874           1926
10      90011            103892        26.2        52794          51098
11      90012             31103        36.3        19493          11610
12      90013             11772        44.6         7629           4143
13      90014              7005        44.8         4471           2534
14      90015             18986        31.3         9833           9153
15      90016             47596        33.9        22778          24818
16      90017             23768        29.4        12818          10950
17      90018             49310        33.2        23770          25540
18      90019             64458        35.8        31442          33016
19      90020             38967        34.6        19381          19586
20      90021              3951        44.3         2790           1161
21      90022             67179        29.8        33216          33963
22      90023             45903        28.4        23037          22866
23      90024             47452        23.6        22248          25204
24      90025             42147        34.7        20859          21288
25      90026             67869        34.0        34515          33354
26      90027             45151        38.3        22362          22789
27      90028             28714        34.0        16056          12658
28      90029             38617        34.6        19575          19042
29      90031             39316        33.5        19546          19770
..        ...               ...         ...          ...            ...
289     91792             30854        35.3        14950          15904
290     91801             52735        39.1        24833          27902
291     91803             30322        39.6        14486          15836
292     92301             32725        25.6        16857          15868
293     92371             16763        37.9         8565           8198
294     92372              6220        41.8         3136           3084
295     92397              4894        44.1         2522           2372
296     92821             35533        38.7        17338          18195
297     92823              3613        38.6         1757           1856
298     92833             51767        36.0        25643          26124
299     93040              2031        29.3         1052            979
300     93063             54366        39.0        26592          27774
301     93225              5077        44.0         2585           2492
302     93243              1699        40.9          884            815
303     93252              4176        38.4         3301            875
304     93510              7993        45.2         4086           3907
305     93523              3074        27.0         1531           1543
306     93532              2932        41.7         1642           1290
307     93534             39341        31.1        18601          20740
308     93535             72046        28.3        34879          37167
309     93536             70918        34.4        37804          33114
310     93543             13033        32.9         6695           6338
311     93544              1259        52.4          689            570
312     93550             74929        27.5        36414          38515
313     93551             50798        37.0        25056          25742
314     93552             38158        28.4        18711          19447
315     93553              2138        43.3         1121           1017
316     93560             18910        32.4         9491           9419
317     93563               388        44.5          263            125
318     93591              7285        30.9         3653           3632

     Total Households  Average Household Size
0                   1                    1.00
1               12971                    4.40
2               11731                    4.36
3               15642                    4.22
4               22547                    2.73
5               15044                    2.50
6               18617                    3.13
7               11944                    3.00
8               13841                    2.33
9                2014                    1.87
10              22168                    4.67
11              10327                    2.12
12               6416                    1.26
13               4109                    1.34
14               7420                    2.45
15              16145                    2.93
16               9338                    2.53
17              15493                    3.12
18              23344                    2.70
19              16514                    2.35
20               1561                    1.57
21              17023                    3.94
22              10727                    4.26
23              17903                    2.03
24              21228                    1.97
25              24956                    2.68
26              21929                    1.99
27              14964                    1.78
28              13883                    2.70
29              11156                    3.49
..                ...                     ...
289              9154                    3.35
290             19315                    2.71
291              9894                    3.04
292              8132                    3.81
293              5370                    3.11
294              2198                    2.83
295              1998                    2.45
296             13062                    2.72
297              1154                    3.13
298             15849                    3.23
299               522                    3.89
300             18650                    2.90
301              2080                    2.44
302               623                    2.73
303               647                    2.81
304              2729                    2.86
305              1056                    2.91
306              1079                    2.45
307             14038                    2.74
308             20672                    3.44
309             20964                    3.07
310              3560                    3.66
311               569                    2.20
312             20864                    3.58
313             15963                    3.18
314              9690                    3.93
315               816                    2.62
316              6469                    2.92
317               103                    2.53
318              1982                    3.67

[319 rows x 7 columns]

In [4]:
df = pd.read_table("./Data/los_census.txt")
print(df)

    Zip Code,Total Population,Median Age,Total Males,Total Females,Total Households,Average Household Size
0                                 91371,1,73.5,0,1,1,1
1               90001,57110,26.6,28468,28642,12971,4.4
2              90002,51223,25.5,24876,26347,11731,4.36
3              90003,66266,26.3,32631,33635,15642,4.22
4              90004,62180,34.8,31302,30878,22547,2.73
5               90005,37681,33.9,19299,18382,15044,2.5
6              90006,59185,32.4,30254,28931,18617,3.13
7                   90007,40920,24,20915,20005,11944,3
8              90008,32327,39.7,14477,17850,13841,2.33
9                  90010,3800,37.8,1874,1926,2014,1.87
10            90011,103892,26.2,52794,51098,22168,4.67
11             90012,31103,36.3,19493,11610,10327,2.12
12                90013,11772,44.6,7629,4143,6416,1.26
13                 90014,7005,44.8,4471,2534,4109,1.34
14                90015,18986,31.3,9833,9153,7420,2.45
15             90016,47596,33.9,22778,24818,16145,2.93
16              90017,23768,29.4,12818,10950,9338,2.53
17             90018,49310,33.2,23770,25540,15493,3.12
18              90019,64458,35.8,31442,33016,23344,2.7
19             90020,38967,34.6,19381,19586,16514,2.35
20                 90021,3951,44.3,2790,1161,1561,1.57
21             90022,67179,29.8,33216,33963,17023,3.94
22             90023,45903,28.4,23037,22866,10727,4.26
23             90024,47452,23.6,22248,25204,17903,2.03
24             90025,42147,34.7,20859,21288,21228,1.97
25               90026,67869,34,34515,33354,24956,2.68
26             90027,45151,38.3,22362,22789,21929,1.99
27               90028,28714,34,16056,12658,14964,1.78
28              90029,38617,34.6,19575,19042,13883,2.7
29             90031,39316,33.5,19546,19770,11156,3.49
..                                                 ...
289             91792,30854,35.3,14950,15904,9154,3.35
290            91801,52735,39.1,24833,27902,19315,2.71
291             91803,30322,39.6,14486,15836,9894,3.04
292             92301,32725,25.6,16857,15868,8132,3.81
293               92371,16763,37.9,8565,8198,5370,3.11
294                92372,6220,41.8,3136,3084,2198,2.83
295                92397,4894,44.1,2522,2372,1998,2.45
296            92821,35533,38.7,17338,18195,13062,2.72
297                92823,3613,38.6,1757,1856,1154,3.13
298              92833,51767,36,25643,26124,15849,3.23
299                  93040,2031,29.3,1052,979,522,3.89
300               93063,54366,39,26592,27774,18650,2.9
301                  93225,5077,44,2585,2492,2080,2.44
302                   93243,1699,40.9,884,815,623,2.73
303                  93252,4176,38.4,3301,875,647,2.81
304                93510,7993,45.2,4086,3907,2729,2.86
305                  93523,3074,27,1531,1543,1056,2.91
306                93532,2932,41.7,1642,1290,1079,2.45
307            93534,39341,31.1,18601,20740,14038,2.74
308            93535,72046,28.3,34879,37167,20672,3.44
309            93536,70918,34.4,37804,33114,20964,3.07
310               93543,13033,32.9,6695,6338,3560,3.66
311                    93544,1259,52.4,689,570,569,2.2
312            93550,74929,27.5,36414,38515,20864,3.58
313              93551,50798,37,25056,25742,15963,3.18
314             93552,38158,28.4,18711,19447,9690,3.93
315                 93553,2138,43.3,1121,1017,816,2.62
316               93560,18910,32.4,9491,9419,6469,2.92
317                    93563,388,44.5,263,125,103,2.53
318                93591,7285,30.9,3653,3632,1982,3.67

[319 rows x 1 columns]

## read_table

In [6]:
df = pd.read_table("./Data/los_census.txt", sep=',')
print(df)

     Zip Code  Total Population  Median Age  Total Males  Total Females  \
0       91371                 1        73.5            0              1
1       90001             57110        26.6        28468          28642
2       90002             51223        25.5        24876          26347
3       90003             66266        26.3        32631          33635
4       90004             62180        34.8        31302          30878
5       90005             37681        33.9        19299          18382
6       90006             59185        32.4        30254          28931
7       90007             40920        24.0        20915          20005
8       90008             32327        39.7        14477          17850
9       90010              3800        37.8         1874           1926
10      90011            103892        26.2        52794          51098
11      90012             31103        36.3        19493          11610
12      90013             11772        44.6         7629           4143
13      90014              7005        44.8         4471           2534
14      90015             18986        31.3         9833           9153
15      90016             47596        33.9        22778          24818
16      90017             23768        29.4        12818          10950
17      90018             49310        33.2        23770          25540
18      90019             64458        35.8        31442          33016
19      90020             38967        34.6        19381          19586
20      90021              3951        44.3         2790           1161
21      90022             67179        29.8        33216          33963
22      90023             45903        28.4        23037          22866
23      90024             47452        23.6        22248          25204
24      90025             42147        34.7        20859          21288
25      90026             67869        34.0        34515          33354
26      90027             45151        38.3        22362          22789
27      90028             28714        34.0        16056          12658
28      90029             38617        34.6        19575          19042
29      90031             39316        33.5        19546          19770
..        ...               ...         ...          ...            ...
289     91792             30854        35.3        14950          15904
290     91801             52735        39.1        24833          27902
291     91803             30322        39.6        14486          15836
292     92301             32725        25.6        16857          15868
293     92371             16763        37.9         8565           8198
294     92372              6220        41.8         3136           3084
295     92397              4894        44.1         2522           2372
296     92821             35533        38.7        17338          18195
297     92823              3613        38.6         1757           1856
298     92833             51767        36.0        25643          26124
299     93040              2031        29.3         1052            979
300     93063             54366        39.0        26592          27774
301     93225              5077        44.0         2585           2492
302     93243              1699        40.9          884            815
303     93252              4176        38.4         3301            875
304     93510              7993        45.2         4086           3907
305     93523              3074        27.0         1531           1543
306     93532              2932        41.7         1642           1290
307     93534             39341        31.1        18601          20740
308     93535             72046        28.3        34879          37167
309     93536             70918        34.4        37804          33114
310     93543             13033        32.9         6695           6338
311     93544              1259        52.4          689            570
312     93550             74929        27.5        36414          38515
313     93551             50798        37.0        25056          25742
314     93552             38158        28.4        18711          19447
315     93553              2138        43.3         1121           1017
316     93560             18910        32.4         9491           9419
317     93563               388        44.5          263            125
318     93591              7285        30.9         3653           3632

     Total Households  Average Household Size
0                   1                    1.00
1               12971                    4.40
2               11731                    4.36
3               15642                    4.22
4               22547                    2.73
5               15044                    2.50
6               18617                    3.13
7               11944                    3.00
8               13841                    2.33
9                2014                    1.87
10              22168                    4.67
11              10327                    2.12
12               6416                    1.26
13               4109                    1.34
14               7420                    2.45
15              16145                    2.93
16               9338                    2.53
17              15493                    3.12
18              23344                    2.70
19              16514                    2.35
20               1561                    1.57
21              17023                    3.94
22              10727                    4.26
23              17903                    2.03
24              21228                    1.97
25              24956                    2.68
26              21929                    1.99
27              14964                    1.78
28              13883                    2.70
29              11156                    3.49
..                ...                     ...
289              9154                    3.35
290             19315                    2.71
291              9894                    3.04
292              8132                    3.81
293              5370                    3.11
294              2198                    2.83
295              1998                    2.45
296             13062                    2.72
297              1154                    3.13
298             15849                    3.23
299               522                    3.89
300             18650                    2.90
301              2080                    2.44
302               623                    2.73
303               647                    2.81
304              2729                    2.86
305              1056                    2.91
306              1079                    2.45
307             14038                    2.74
308             20672                    3.44
309             20964                    3.07
310              3560                    3.66
311               569                    2.20
312             20864                    3.58
313             15963                    3.18
314              9690                    3.93
315               816                    2.62
316              6469                    2.92
317               103                    2.53
318              1982                    3.67

[319 rows x 7 columns]

In [9]:
df = pd.read_csv("./Data/los_census.csv", header=1)
print(df)

     91371       1  73.5      0    1.1    1.2   1.3
0    90001   57110  26.6  28468  28642  12971  4.40
1    90002   51223  25.5  24876  26347  11731  4.36
2    90003   66266  26.3  32631  33635  15642  4.22
3    90004   62180  34.8  31302  30878  22547  2.73
4    90005   37681  33.9  19299  18382  15044  2.50
5    90006   59185  32.4  30254  28931  18617  3.13
6    90007   40920  24.0  20915  20005  11944  3.00
7    90008   32327  39.7  14477  17850  13841  2.33
8    90010    3800  37.8   1874   1926   2014  1.87
9    90011  103892  26.2  52794  51098  22168  4.67
10   90012   31103  36.3  19493  11610  10327  2.12
11   90013   11772  44.6   7629   4143   6416  1.26
12   90014    7005  44.8   4471   2534   4109  1.34
13   90015   18986  31.3   9833   9153   7420  2.45
14   90016   47596  33.9  22778  24818  16145  2.93
15   90017   23768  29.4  12818  10950   9338  2.53
16   90018   49310  33.2  23770  25540  15493  3.12
17   90019   64458  35.8  31442  33016  23344  2.70
18   90020   38967  34.6  19381  19586  16514  2.35
19   90021    3951  44.3   2790   1161   1561  1.57
20   90022   67179  29.8  33216  33963  17023  3.94
21   90023   45903  28.4  23037  22866  10727  4.26
22   90024   47452  23.6  22248  25204  17903  2.03
23   90025   42147  34.7  20859  21288  21228  1.97
24   90026   67869  34.0  34515  33354  24956  2.68
25   90027   45151  38.3  22362  22789  21929  1.99
26   90028   28714  34.0  16056  12658  14964  1.78
27   90029   38617  34.6  19575  19042  13883  2.70
28   90031   39316  33.5  19546  19770  11156  3.49
29   90032   45786  32.4  22564  23222  12765  3.52
..     ...     ...   ...    ...    ...    ...   ...
288  91792   30854  35.3  14950  15904   9154  3.35
289  91801   52735  39.1  24833  27902  19315  2.71
290  91803   30322  39.6  14486  15836   9894  3.04
291  92301   32725  25.6  16857  15868   8132  3.81
292  92371   16763  37.9   8565   8198   5370  3.11
293  92372    6220  41.8   3136   3084   2198  2.83
294  92397    4894  44.1   2522   2372   1998  2.45
295  92821   35533  38.7  17338  18195  13062  2.72
296  92823    3613  38.6   1757   1856   1154  3.13
297  92833   51767  36.0  25643  26124  15849  3.23
298  93040    2031  29.3   1052    979    522  3.89
299  93063   54366  39.0  26592  27774  18650  2.90
300  93225    5077  44.0   2585   2492   2080  2.44
301  93243    1699  40.9    884    815    623  2.73
302  93252    4176  38.4   3301    875    647  2.81
303  93510    7993  45.2   4086   3907   2729  2.86
304  93523    3074  27.0   1531   1543   1056  2.91
305  93532    2932  41.7   1642   1290   1079  2.45
306  93534   39341  31.1  18601  20740  14038  2.74
307  93535   72046  28.3  34879  37167  20672  3.44
308  93536   70918  34.4  37804  33114  20964  3.07
309  93543   13033  32.9   6695   6338   3560  3.66
310  93544    1259  52.4    689    570    569  2.20
311  93550   74929  27.5  36414  38515  20864  3.58
312  93551   50798  37.0  25056  25742  15963  3.18
313  93552   38158  28.4  18711  19447   9690  3.93
314  93553    2138  43.3   1121   1017    816  2.62
315  93560   18910  32.4   9491   9419   6469  2.92
316  93563     388  44.5    263    125    103  2.53
317  93591    7285  30.9   3653   3632   1982  3.67

[318 rows x 7 columns]

In [11]:
# 自定义索引名称
df = pd.read_csv("./Data/los_census.csv", names=['A','B','C','D','E','F','G'])
print(df)

            A                 B           C            D              E  \
0    Zip Code  Total Population  Median Age  Total Males  Total Females
1       91371                 1        73.5            0              1
2       90001             57110        26.6        28468          28642
3       90002             51223        25.5        24876          26347
4       90003             66266        26.3        32631          33635
5       90004             62180        34.8        31302          30878
6       90005             37681        33.9        19299          18382
7       90006             59185        32.4        30254          28931
8       90007             40920          24        20915          20005
9       90008             32327        39.7        14477          17850
10      90010              3800        37.8         1874           1926
11      90011            103892        26.2        52794          51098
12      90012             31103        36.3        19493          11610
13      90013             11772        44.6         7629           4143
14      90014              7005        44.8         4471           2534
15      90015             18986        31.3         9833           9153
16      90016             47596        33.9        22778          24818
17      90017             23768        29.4        12818          10950
18      90018             49310        33.2        23770          25540
19      90019             64458        35.8        31442          33016
20      90020             38967        34.6        19381          19586
21      90021              3951        44.3         2790           1161
22      90022             67179        29.8        33216          33963
23      90023             45903        28.4        23037          22866
24      90024             47452        23.6        22248          25204
25      90025             42147        34.7        20859          21288
26      90026             67869          34        34515          33354
27      90027             45151        38.3        22362          22789
28      90028             28714          34        16056          12658
29      90029             38617        34.6        19575          19042
..        ...               ...         ...          ...            ...
290     91792             30854        35.3        14950          15904
291     91801             52735        39.1        24833          27902
292     91803             30322        39.6        14486          15836
293     92301             32725        25.6        16857          15868
294     92371             16763        37.9         8565           8198
295     92372              6220        41.8         3136           3084
296     92397              4894        44.1         2522           2372
297     92821             35533        38.7        17338          18195
298     92823              3613        38.6         1757           1856
299     92833             51767          36        25643          26124
300     93040              2031        29.3         1052            979
301     93063             54366          39        26592          27774
302     93225              5077          44         2585           2492
303     93243              1699        40.9          884            815
304     93252              4176        38.4         3301            875
305     93510              7993        45.2         4086           3907
306     93523              3074          27         1531           1543
307     93532              2932        41.7         1642           1290
308     93534             39341        31.1        18601          20740
309     93535             72046        28.3        34879          37167
310     93536             70918        34.4        37804          33114
311     93543             13033        32.9         6695           6338
312     93544              1259        52.4          689            570
313     93550             74929        27.5        36414          38515
314     93551             50798          37        25056          25742
315     93552             38158        28.4        18711          19447
316     93553              2138        43.3         1121           1017
317     93560             18910        32.4         9491           9419
318     93563               388        44.5          263            125
319     93591              7285        30.9         3653           3632

                    F                       G
0    Total Households  Average Household Size
1                   1                       1
2               12971                     4.4
3               11731                    4.36
4               15642                    4.22
5               22547                    2.73
6               15044                     2.5
7               18617                    3.13
8               11944                       3
9               13841                    2.33
10               2014                    1.87
11              22168                    4.67
12              10327                    2.12
13               6416                    1.26
14               4109                    1.34
15               7420                    2.45
16              16145                    2.93
17               9338                    2.53
18              15493                    3.12
19              23344                     2.7
20              16514                    2.35
21               1561                    1.57
22              17023                    3.94
23              10727                    4.26
24              17903                    2.03
25              21228                    1.97
26              24956                    2.68
27              21929                    1.99
28              14964                    1.78
29              13883                     2.7
..                ...                     ...
290              9154                    3.35
291             19315                    2.71
292              9894                    3.04
293              8132                    3.81
294              5370                    3.11
295              2198                    2.83
296              1998                    2.45
297             13062                    2.72
298              1154                    3.13
299             15849                    3.23
300               522                    3.89
301             18650                     2.9
302              2080                    2.44
303               623                    2.73
304               647                    2.81
305              2729                    2.86
306              1056                    2.91
307              1079                    2.45
308             14038                    2.74
309             20672                    3.44
310             20964                    3.07
311              3560                    3.66
312               569                     2.2
313             20864                    3.58
314             15963                    3.18
315              9690                    3.93
316               816                    2.62
317              6469                    2.92
318               103                    2.53
319              1982                    3.67

[320 rows x 7 columns]

## to_json

In [10]:
df.to_json("./Data/1.json")

# 2. Head & Tail

In [12]:
df = pd.read_csv("./Data/los_census.csv")

print(df.head())
print(df.head(7))

   Zip Code  Total Population  Median Age  Total Males  Total Females  \
0     91371                 1        73.5            0              1
1     90001             57110        26.6        28468          28642
2     90002             51223        25.5        24876          26347
3     90003             66266        26.3        32631          33635
4     90004             62180        34.8        31302          30878

   Total Households  Average Household Size
0                 1                    1.00
1             12971                    4.40
2             11731                    4.36
3             15642                    4.22
4             22547                    2.73
   Zip Code  Total Population  Median Age  Total Males  Total Females  \
0     91371                 1        73.5            0              1
1     90001             57110        26.6        28468          28642
2     90002             51223        25.5        24876          26347
3     90003             66266        26.3        32631          33635
4     90004             62180        34.8        31302          30878
5     90005             37681        33.9        19299          18382
6     90006             59185        32.4        30254          28931

   Total Households  Average Household Size
0                 1                    1.00
1             12971                    4.40
2             11731                    4.36
3             15642                    4.22
4             22547                    2.73
5             15044                    2.50
6             18617                    3.13

In [13]:
print(df.tail())
print(df.tail(7))

     Zip Code  Total Population  Median Age  Total Males  Total Females  \
314     93552             38158        28.4        18711          19447
315     93553              2138        43.3         1121           1017
316     93560             18910        32.4         9491           9419
317     93563               388        44.5          263            125
318     93591              7285        30.9         3653           3632

     Total Households  Average Household Size
314              9690                    3.93
315               816                    2.62
316              6469                    2.92
317               103                    2.53
318              1982                    3.67
     Zip Code  Total Population  Median Age  Total Males  Total Females  \
312     93550             74929        27.5        36414          38515
313     93551             50798        37.0        25056          25742
314     93552             38158        28.4        18711          19447
315     93553              2138        43.3         1121           1017
316     93560             18910        32.4         9491           9419
317     93563               388        44.5          263            125
318     93591              7285        30.9         3653           3632

     Total Households  Average Household Size
312             20864                    3.58
313             15963                    3.18
314              9690                    3.93
315               816                    2.62
316              6469                    2.92
317               103                    2.53
318              1982                    3.67

# 3. Statistic

## 3.1 describe()

In [14]:
df.describe()

,Zip Code,Total Population,Median Age,Total Males,Total Females,Total Households,Average Household Size
count,319.000000,319.000000,319.000000,319.000000,319.000000,319.000000,319.000000
mean,91000.673981,33241.341693,36.527586,16391.564263,16849.777429,10964.570533,2.828119
std,908.360203,21644.417455,8.692999,10747.495566,10934.986468,6270.646400,0.835658
min,90001.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,90243.500000,19318.500000,32.400000,9763.500000,9633.500000,6765.500000,2.435000
50%,90807.000000,31481.000000,37.100000,15283.000000,16202.000000,10968.000000,2.830000
75%,91417.000000,44978.000000,41.000000,22219.500000,22690.500000,14889.500000,3.320000
max,93591.000000,105549.000000,74.000000,52794.000000,53185.000000,31087.000000,4.670000

## 3.2 idxmin() & idxmax()

In [15]:
print(df.idxmin())
print(df.idxmax())

Zip Code                   1
Total Population          64
Median Age                64
Total Males                0
Total Females             64
Total Households          61
Average Household Size    61
dtype: int64
Zip Code                  318
Total Population          132
Median Age                180
Total Males                10
Total Females             132
Total Households           85
Average Household Size     10
dtype: int64

## 3.3 count()

In [16]:
df.count()

Zip Code                  319
Total Population          319
Median Age                319
Total Males               319
Total Females             319
Total Households          319
Average Household Size    319
dtype: int64

## 3.4 value_counts()

In [19]:
import numpy as np

s = pd.Series(np.random.randint(0, 9, size=100))

print(s)
print(s.value_counts)

0     7
1     5
2     0
3     5
4     1
5     0
6     7
7     7
8     8
9     6
10    2
11    3
12    1
13    4
14    8
15    6
16    4
17    7
18    8
19    5
20    3
21    4
22    1
23    3
24    8
25    2
26    2
27    2
28    0
29    1
     ..
70    7
71    8
72    2
73    0
74    6
75    7
76    8
77    8
78    6
79    7
80    1
81    2
82    6
83    7
84    8
85    3
86    8
87    4
88    3
89    1
90    5
91    0
92    4
93    2
94    4
95    8
96    7
97    5
98    2
99    7
Length: 100, dtype: int32
<bound method IndexOpsMixin.value_counts of 0     7
1     5
2     0
3     5
4     1
5     0
6     7
7     7
8     8
9     6
10    2
11    3
12    1
13    4
14    8
15    6
16    4
17    7
18    8
19    5
20    3
21    4
22    1
23    3
24    8
25    2
26    2
27    2
28    0
29    1
     ..
70    7
71    8
72    2
73    0
74    6
75    7
76    8
77    8
78    6
79    7
80    1
81    2
82    6
83    7
84    8
85    3
86    8
87    4
88    3
89    1
90    5
91    0
92    4
93    2
94    4
95    8
96    7
97    5
98    2
99    7
Length: 100, dtype: int32>

# 4. Math Function

## 4.1 sum()

In [20]:
df.sum()

Zip Code                  29029215.00
Total Population          10603988.00
Median Age                   11652.30
Total Males                5228909.00
Total Females              5375079.00
Total Households           3497698.00
Average Household Size         902.17
dtype: float64

## 4.2 mean()

In [21]:
df.mean()

Zip Code                  91000.673981
Total Population          33241.341693
Median Age                   36.527586
Total Males               16391.564263
Total Females             16849.777429
Total Households          10964.570533
Average Household Size        2.828119
dtype: float64

## 4.3 median()

In [22]:
df.median()

Zip Code                  90807.00
Total Population          31481.00
Median Age                   37.10
Total Males               15283.00
Total Females             16202.00
Total Households          10968.00
Average Household Size        2.83
dtype: float64

## 4.4 贝塞尔校正样本标准偏差 std()

In [23]:
df.std()

Zip Code                    908.360203
Total Population          21644.417455
Median Age                    8.692999
Total Males               10747.495566
Total Females             10934.986468
Total Households           6270.646400
Average Household Size        0.835658
dtype: float64

## 4.5 无偏差 var()

In [24]:
df.var()

Zip Code                  8.251183e+05
Total Population          4.684808e+08
Median Age                7.556823e+01
Total Males               1.155087e+08
Total Females             1.195739e+08
Total Households          3.932101e+07
Average Household Size    6.983248e-01
dtype: float64

## 4.6 平均值标准误差 sem()

In [25]:
df.sem()

Zip Code                    50.858407
Total Population          1211.854724
Median Age                   0.486714
Total Males                601.744228
Total Females              612.241703
Total Households           351.088796
Average Household Size       0.046788
dtype: float64

## 4.7 偏度 skew()

In [27]:
df.skew()

Zip Code                  1.128873
Total Population          0.794884
Median Age               -0.606692
Total Males               0.831140
Total Females             0.759765
Total Households          0.259914
Average Household Size   -0.673633
dtype: float64

## 4.8 峰度 kurt()

In [28]:
df.kurt()

Zip Code                  1.082875
Total Population          0.829156
Median Age                6.659417
Total Males               0.906265
Total Females             0.753626
Total Households         -0.073866
Average Household Size    1.881002
dtype: float64

# 5. 标签对齐

In [26]:
s = pd.Series(data=[1,2,3,4,5], index=['a','b','c','d','e'])

print(s)
print(s.reindex(['e', 'b', 'f', 'd']))

a    1
b    2
c    3
d    4
e    5
dtype: int64
e    5.0
b    2.0
f    NaN
d    4.0
dtype: float64

In [29]:
df = pd.DataFrame(data={'one':[1,2,3], 'two':[4,5,6], 'three':[7,8,9]}, index=['a','b','c'])

print(df)

   one  three  two
a    1      7    4
b    2      8    5
c    3      9    6

In [30]:
print(df.reindex(index=['b','c','a'], columns=['three', 'two', 'one']))

   three  two  one
b      8    5    2
c      9    6    3
a      7    4    1

In [31]:
print(s.reindex(df.index))

a    1
b    2
c    3
dtype: int64

# 6. Sort

In [32]:
df = pd.DataFrame(data={'one':[1,2,3], 'two':[4,5,6], 'three':[7,8,9], 'four':[10,11,12]}, index=['a','b','c'])

print(df)

   four  one  three  two
a    10    1      7    4
b    11    2      8    5
c    12    3      9    6

In [34]:
print(df.sort_index())

   four  one  three  two
a    10    1      7    4
b    11    2      8    5
c    12    3      9    6

In [35]:
print(df.sort_index(ascending=False))

   four  one  three  two
c    12    3      9    6
b    11    2      8    5
a    10    1      7    4

In [37]:
df = pd.DataFrame(data={'one': [1, 2, 3, 7], 'two': [4, 5, 6, 9], 'three': [7, 8, 9, 2], 'four': [10, 11, 12, 5]}, index=['a', 'c', 'b','d'])

print(df)

   four  one  three  two
a    10    1      7    4
c    11    2      8    5
b    12    3      9    6
d     5    7      2    9

In [38]:
print(df.sort_values(by='three'))

   four  one  three  two
d     5    7      2    9
a    10    1      7    4
c    11    2      8    5
b    12    3      9    6

In [39]:
print(df[['one','two','three','four']].sort_values(by=['one','two']))

   one  two  three  four
a    1    4      7    10
c    2    5      8    11
b    3    6      9    12
d    7    9      2     5